# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor_analytics', '0002_auto_20170127_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='response_data',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
